### ISSUE TITLE
Getting TLS Pointer crashes MCC

### ISSUE THREAD

**Issue by matty45** [matty45/Drinol#43]
To reproduce:
1. Start a game in mcc then go into gameplay.
2. End the game and switch to another one.
3. Trigger utils::get_tls_pointer.
4. Game will crash.

**Comment by TempAccountNull** [comment]
Other notes:

Requires a fix to the TLSIndex as it cannot be null. The game slowly changes it eventually dependent on what user selects but if that user goes too fast then the index is not written and the game will panic, so figure out a way we can check it so **Get_Tls_Pointer** only returns and fails to call to prevent crashing.

**Comment by xCENTx** [comment]
My latest pull request resolves this issue.

The problem lies in the initial tlsPointer variable. It is initialized as static within the function/. When the function clears the value is not cleared. Upon the function executing a second time the original pointer is loaded and therefore since TLSPointer is not null it does not try to obtain an index

Issue was resolved by removing the static keyword

https://github.com/matty45/Drinol/blob/7f8b9429b489f6405b7daea2e7e3b3b8a18d37ea/utils/utils.cpp#L180
